apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux           # usa Flux query language (InfluxDB 2.x)
      organization: tcc-iot
      defaultBucket: sensor_readings
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
